[build]
  # Use the build script defined in package.json
  command = "npm run build:netlify"
  # Specify the directory containing the built site assets
  publish = "dist"
  # Specify the custom vite config file for Netlify build
  # Note: Netlify's build environment might handle this differently,
  # but explicitly setting NODE_ENV can sometimes help.
  environment = { NODE_ENV = "production" }

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Redirect all non-file requests to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
