[build]
base = "client"
command = "npm install && npm run build"
publish = "dist"
environment = { NODE_VERSION = "18" }

[[redirects]]
from = "/"
to = "/index.html"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true 