[build]
  command = "chmod +x ./build-netlify.sh && ./build-netlify.sh"
  publish = "dist"
  ignore_warnings = true

[build.environment]
  ROLLUP_SKIP_NATIVE = "true"
  NODE_OPTIONS = "--max_old_space_size=4096"
  VITE_APP_HOME_PATH = "/client/src/pages/Home.tsx"
  VITE_DEPLOYMENT = "netlify"
  NODE_ENV = "production"
  DISABLE_BINARY = "true"
  npm_config_platform = "linux"

# Configurações para o SPA routing
# Isso garante que o roteamento do lado do cliente funcione corretamente

# Redirecionamento de páginas com 'Sistema de Gestão Escolar'
[[redirects]]
  from = "/Sistema*"
  to = "/"
  status = 301
  force = true

# Redirecionamento principal para rotas SPA (deve ser o último)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 