[build]
  # Run our simplified build script
  command = "chmod +x ./build-netlify.sh && ./build-netlify.sh"
  # Output directory
  publish = "dist"

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
