[build]
  # Run our build script
  command = "chmod +x ./build-netlify.sh && ./build-netlify.sh"
  # Output directory
  publish = "dist"
  # Environment variables to help the build
  environment = { NODE_VERSION = "18" }

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
