[build]
  command = "chmod +x ./netlify-fix.sh && ./netlify-fix.sh || (mkdir -p dist && cp emergency.html dist/index.html || echo '<html><body>Emergency fallback</body></html>' > dist/index.html)"
  publish = "dist"

[build.environment]
  ROLLUP_SKIP_NATIVE = "true"
  NODE_OPTIONS = "--max_old_space_size=4096"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 